/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QrTokenRouteImport } from './routes/qr/$token'
import { Route as ReportsVerifyReportIdRouteImport } from './routes/reports/verify.$reportId'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedGroupsRouteImport } from './routes/_authed/groups'
import { Route as AuthedEventsRouteImport } from './routes/_authed/events'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDevicesIndexRouteImport } from './routes/_authed/devices/index'
import { Route as AuthedSettingsTenantRouteImport } from './routes/_authed/settings/tenant'
import { Route as AuthedSettingsProfileRouteImport } from './routes/_authed/settings/profile'
import { Route as AuthedSettingsNotificationsRouteImport } from './routes/_authed/settings/notifications'
import { Route as AuthedDevicesDeviceIdRouteImport } from './routes/_authed/devices/$deviceId'
import { Route as AuthedAdminTenantsRouteImport } from './routes/_authed/admin/tenants'
import { Route as AuthedAdminDevicesGlobalRouteImport } from './routes/_authed/admin/devices-global'
import { Route as AuthedSettingsThresholdsDeviceIdRouteImport } from './routes/_authed/settings/thresholds/$deviceId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrTokenRoute = QrTokenRouteImport.update({
  id: '/qr/$token',
  path: '/qr/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsVerifyReportIdRoute = ReportsVerifyReportIdRouteImport.update({
  id: '/reports/verify/$reportId',
  path: '/reports/verify/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedGroupsRoute = AuthedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEventsRoute = AuthedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedDevicesIndexRoute = AuthedDevicesIndexRouteImport.update({
  id: '/devices/',
  path: '/devices/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsTenantRoute = AuthedSettingsTenantRouteImport.update({
  id: '/settings/tenant',
  path: '/settings/tenant',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsProfileRoute = AuthedSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedSettingsNotificationsRoute =
  AuthedSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedDevicesDeviceIdRoute = AuthedDevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminTenantsRoute = AuthedAdminTenantsRouteImport.update({
  id: '/admin/tenants',
  path: '/admin/tenants',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAdminDevicesGlobalRoute =
  AuthedAdminDevicesGlobalRouteImport.update({
    id: '/admin/devices-global',
    path: '/admin/devices-global',
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedSettingsThresholdsDeviceIdRoute =
  AuthedSettingsThresholdsDeviceIdRouteImport.update({
    id: '/settings/thresholds/$deviceId',
    path: '/settings/thresholds/$deviceId',
    getParentRoute: () => AuthedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/events': typeof AuthedEventsRoute
  '/groups': typeof AuthedGroupsRoute
  '/users': typeof AuthedUsersRoute
  '/qr/$token': typeof QrTokenRoute
  '/reports/verify/$reportId': typeof ReportsVerifyReportIdRoute
  '/admin/devices-global': typeof AuthedAdminDevicesGlobalRoute
  '/admin/tenants': typeof AuthedAdminTenantsRoute
  '/devices/$deviceId': typeof AuthedDevicesDeviceIdRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/tenant': typeof AuthedSettingsTenantRoute
  '/devices/': typeof AuthedDevicesIndexRoute
  '/settings/thresholds/$deviceId': typeof AuthedSettingsThresholdsDeviceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/events': typeof AuthedEventsRoute
  '/groups': typeof AuthedGroupsRoute
  '/users': typeof AuthedUsersRoute
  '/qr/$token': typeof QrTokenRoute
  '/reports/verify/$reportId': typeof ReportsVerifyReportIdRoute
  '/admin/devices-global': typeof AuthedAdminDevicesGlobalRoute
  '/admin/tenants': typeof AuthedAdminTenantsRoute
  '/devices/$deviceId': typeof AuthedDevicesDeviceIdRoute
  '/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/settings/profile': typeof AuthedSettingsProfileRoute
  '/settings/tenant': typeof AuthedSettingsTenantRoute
  '/devices': typeof AuthedDevicesIndexRoute
  '/settings/thresholds/$deviceId': typeof AuthedSettingsThresholdsDeviceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/events': typeof AuthedEventsRoute
  '/_authed/groups': typeof AuthedGroupsRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/qr/$token': typeof QrTokenRoute
  '/reports/verify/$reportId': typeof ReportsVerifyReportIdRoute
  '/_authed/admin/devices-global': typeof AuthedAdminDevicesGlobalRoute
  '/_authed/admin/tenants': typeof AuthedAdminTenantsRoute
  '/_authed/devices/$deviceId': typeof AuthedDevicesDeviceIdRoute
  '/_authed/settings/notifications': typeof AuthedSettingsNotificationsRoute
  '/_authed/settings/profile': typeof AuthedSettingsProfileRoute
  '/_authed/settings/tenant': typeof AuthedSettingsTenantRoute
  '/_authed/devices/': typeof AuthedDevicesIndexRoute
  '/_authed/settings/thresholds/$deviceId': typeof AuthedSettingsThresholdsDeviceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/events'
    | '/groups'
    | '/users'
    | '/qr/$token'
    | '/reports/verify/$reportId'
    | '/admin/devices-global'
    | '/admin/tenants'
    | '/devices/$deviceId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/tenant'
    | '/devices/'
    | '/settings/thresholds/$deviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/events'
    | '/groups'
    | '/users'
    | '/qr/$token'
    | '/reports/verify/$reportId'
    | '/admin/devices-global'
    | '/admin/tenants'
    | '/devices/$deviceId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/tenant'
    | '/devices'
    | '/settings/thresholds/$deviceId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/events'
    | '/_authed/groups'
    | '/_authed/users'
    | '/qr/$token'
    | '/reports/verify/$reportId'
    | '/_authed/admin/devices-global'
    | '/_authed/admin/tenants'
    | '/_authed/devices/$deviceId'
    | '/_authed/settings/notifications'
    | '/_authed/settings/profile'
    | '/_authed/settings/tenant'
    | '/_authed/devices/'
    | '/_authed/settings/thresholds/$deviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  QrTokenRoute: typeof QrTokenRoute
  ReportsVerifyReportIdRoute: typeof ReportsVerifyReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$token': {
      id: '/qr/$token'
      path: '/qr/$token'
      fullPath: '/qr/$token'
      preLoaderRoute: typeof QrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/verify/$reportId': {
      id: '/reports/verify/$reportId'
      path: '/reports/verify/$reportId'
      fullPath: '/reports/verify/$reportId'
      preLoaderRoute: typeof ReportsVerifyReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/groups': {
      id: '/_authed/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthedGroupsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/events': {
      id: '/_authed/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthedEventsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/devices/': {
      id: '/_authed/devices/'
      path: '/devices'
      fullPath: '/devices/'
      preLoaderRoute: typeof AuthedDevicesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/tenant': {
      id: '/_authed/settings/tenant'
      path: '/settings/tenant'
      fullPath: '/settings/tenant'
      preLoaderRoute: typeof AuthedSettingsTenantRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/profile': {
      id: '/_authed/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthedSettingsProfileRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/notifications': {
      id: '/_authed/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthedSettingsNotificationsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/devices/$deviceId': {
      id: '/_authed/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof AuthedDevicesDeviceIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/tenants': {
      id: '/_authed/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthedAdminTenantsRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/admin/devices-global': {
      id: '/_authed/admin/devices-global'
      path: '/admin/devices-global'
      fullPath: '/admin/devices-global'
      preLoaderRoute: typeof AuthedAdminDevicesGlobalRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/settings/thresholds/$deviceId': {
      id: '/_authed/settings/thresholds/$deviceId'
      path: '/settings/thresholds/$deviceId'
      fullPath: '/settings/thresholds/$deviceId'
      preLoaderRoute: typeof AuthedSettingsThresholdsDeviceIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedEventsRoute: typeof AuthedEventsRoute
  AuthedGroupsRoute: typeof AuthedGroupsRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedAdminDevicesGlobalRoute: typeof AuthedAdminDevicesGlobalRoute
  AuthedAdminTenantsRoute: typeof AuthedAdminTenantsRoute
  AuthedDevicesDeviceIdRoute: typeof AuthedDevicesDeviceIdRoute
  AuthedSettingsNotificationsRoute: typeof AuthedSettingsNotificationsRoute
  AuthedSettingsProfileRoute: typeof AuthedSettingsProfileRoute
  AuthedSettingsTenantRoute: typeof AuthedSettingsTenantRoute
  AuthedDevicesIndexRoute: typeof AuthedDevicesIndexRoute
  AuthedSettingsThresholdsDeviceIdRoute: typeof AuthedSettingsThresholdsDeviceIdRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedEventsRoute: AuthedEventsRoute,
  AuthedGroupsRoute: AuthedGroupsRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedAdminDevicesGlobalRoute: AuthedAdminDevicesGlobalRoute,
  AuthedAdminTenantsRoute: AuthedAdminTenantsRoute,
  AuthedDevicesDeviceIdRoute: AuthedDevicesDeviceIdRoute,
  AuthedSettingsNotificationsRoute: AuthedSettingsNotificationsRoute,
  AuthedSettingsProfileRoute: AuthedSettingsProfileRoute,
  AuthedSettingsTenantRoute: AuthedSettingsTenantRoute,
  AuthedDevicesIndexRoute: AuthedDevicesIndexRoute,
  AuthedSettingsThresholdsDeviceIdRoute: AuthedSettingsThresholdsDeviceIdRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  QrTokenRoute: QrTokenRoute,
  ReportsVerifyReportIdRoute: ReportsVerifyReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
