node {
  name = "emqx@127.0.0.1"
  cookie = "wcreation_prod_cookie"
  data_dir = "/opt/emqx/data"
}

cluster {
  discovery_strategy = manual
}

dashboard {
  listeners {
    http {
      bind = "0.0.0.0:18083"
    }
  }
}

mqtt {
  peer_cert_as_username = "cn"
}

listeners.ws.default {
  enable = false
}

listeners.wss.default {
  enable = false
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
  enable_authn = false
}

listeners.ssl.default {
  bind = "0.0.0.0:8883"
  max_connections = 1024000
  enable_authn = false
  ssl_options {
    certfile = "/mnt/wcreation-certs/broker/server.crt"
    keyfile = "/mnt/wcreation-certs/broker/server.key"
    cacertfile = "/mnt/wcreation-certs/broker/cacert.pem"
    verify = verify_peer
    fail_if_no_peer_cert = true
  }
}

authentication = [
  {
    enable = false
    mechanism = password_based
    backend = built_in_database
  }
]

authorization {
  no_match = deny
  sources = [
    {
      type = file
      enable = true
      path = "/opt/emqx/etc/acl.conf"
    }
  ]
}
